name: release
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
  
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and install
      run: make install

    - name: Test ACC and Unit Test
      run: make testacc
      env:
        TF_LOG: TRACE
        TF_ACC: 1
        KIBANA_URL: ${{ secrets.KIBANA_URL }}
        CLOUD_AUTH: ${{ secrets.CLOUD_AUTH }}
        TF_VAR_cloud_id: ${{ secrets.ELASTIC_CLOUD_ID }}

    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


